services:
  egm-bank-server:
    image: wildace/egm-bank-server:latest
    container_name: egm-bank-server
    ports:
      - "9001:9001"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    command: ["sh", "-c", "/script.sh"]
