services: # Different services that make up your application
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - 2717:27017
    volumes:
      - ./databases/mongo1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mydatabase
    restart: unless-stopped

  mongo-express-1:
    image: mongo-express
    container_name: mongo-express-1
    ports:
      - 8081:8081
    depends_on:
      mongo1:
        condition: service_started
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 172.17.0.1
      ME_CONFIG_MONGODB_PORT: 2717
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: q
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
